image: node:16

cache:
  paths:
    - node_modules/

before_script:
  - npm install

stages:
  - build
  - test

build:
  stage: build
  tags:
    - dind
  artifacts:
    paths:
      - dist
  script:
    - echo "Building"
    - npm run build

test:
  stage: test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  tags:
    - dind
  script:
    - echo "Testing"
    - npm run test:report
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml
  dependencies:
    - build
